var kar = new Audio();
kar.src = 'kar-98.mp3';

var awm = new Audio();
awm.src = 'AWM.mp3';

var m24 = new Audio();
m24.src = 'm24.mp3';

var groza = new Audio();
groza.src = 'groza.mp3';

var m416 = new Audio();
m416.src = 'm416.mp3';

var m762 = new Audio();
m762.src = 'm762.mp3';

var scarl = new Audio();
scarl.src = 'scarl.mp3';

var akm = new Audio();
akm.src = 'akm.mp3';

var dp = new Audio();
dp.src = 'dp28.mp3';

var aug = new Audio();
aug.src = 'aug.mp3';

var m16 = new Audio();
m16.src = 'm16.mp3';

var m249 = new Audio();
m249.src = 'm249.mp3';